In [45]:
import os
os.system('cls||clear')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# list_a = [1,2,3,4,5]
# print(list_a)
# print(type(list_a))

# # Convert into Array using Numpy
# array_a = np.array(list_a)
# print(type(array_a))

# new_array = array_a * 2
# print(new_array)

# # Creating a dataframe
# series_a = pd.Series([1,2,3,4,5,6], index = ('a','b','c','d','e','f'))
# print(series_a)

# Creating a dataframe
#df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6],"c":[7,8,9]}, index = ['x','y','z'])
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index = ['x','y','z'], columns = ['a','b','c'])
print(df.head())
print(df.tail(1))

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9
   a  b  c
z  7  8  9

sh: cls: command not found

In [46]:
#read csv file
df = pd.read_csv('insurance.csv')
print(df.head())

#Plot a graph using sns
# sns.relplot(data=df, x='sex', y='age')

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [47]:
df.iloc[7:10,[2,5]]
df[df['age'] > 63]

      age     sex     bmi  children smoker     region      charges
62     64    male  24.700         1     no  northwest  30166.61817
94     64  female  31.300         2    yes  southwest  47291.05500
199    64  female  39.330         0     no  northeast  14901.51670
328    64  female  33.800         1    yes  southwest  47928.03000
335    64    male  34.500         0     no  southwest  13822.80300
378    64  female  30.115         3     no  northwest  16455.70785
398    64    male  25.600         2     no  southwest  14988.43200
402    64  female  32.965         0     no  northwest  14692.66935
418    64    male  39.160         1     no  southeast  14418.28040
420    64    male  33.880         0    yes  southeast  46889.26120
534    64    male  40.480         0     no  southeast  13831.11520
603    64  female  39.050         3     no  southeast  16085.12750
635    64    male  38.190         0     no  northeast  14410.93210
664    64  female  22.990         0    yes  southeast  27037.91410
752    64    male  37.905         0     no  northwest  14210.53595
768    64  female  39.700         0     no  southwest  14319.03100
801    64  female  35.970         0     no  southeast  14313.84630
825    64  female  31.825         2     no  northeast  16069.08475
890    64  female  26.885         0    yes  northwest  29330.98315
1051   64    male  26.410         0     no  northeast  14394.55790
1241   64    male  36.960         2    yes  southeast  49577.66240
1265   64    male  23.760         0    yes  southeast  26926.51440